# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 03:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=100)),
                ('semestre', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo')], max_length=1)),
                ('modalidad', models.CharField(choices=[('D', 'Diurno'), ('V', 'Vespertino'), ('T', 'Tesista')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, default='OEM', max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
