# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pannol', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(default=None, null=True)),
                ('fecha_devolucion', models.DateTimeField(default=None, null=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pannol.Producto')),
            ],
        ),
    ]
